language: ruby
rvm:
  - 2.3.4
  - 2.4.1
before_install:
  - gem install bundler -v 1.15.3
before_script:
  - cd spec/dummy
  - bundle exec rake db:migrate RAILS_ENV=test
  - cd ../..
script: bundle exec rspec
