language: ruby
services:
  - mongodb
rvm:
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/active_record.gemfile
  - gemfiles/mongoid.gemfile
before_script:
  - cd spec/dummy
  - bundle exec rake db:migrate RAILS_ENV=test
  - cd ../..
script: bundle exec rspec
